apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
      {{- include "ctfd.labels" . | nindent 4 }}
type: Opaque
data:
  flaskSecretKey: {{ include "ctfd.secret.flaskSecretKey" . | b64enc | quote }}