---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "ctfd.fullname" . }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ctfd.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "ctfd.fullname" . }}