{{- if .Values.secrets.vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ include "ctfd.fullname" . }}
spec:
  address: {{ .Values.secrets.vault.address | quote }}
  skipTLSVerify: {{ .Values.secrets.vault.skipTLSVerify }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "ctfd.fullname" . }}
spec:
  vaultConnectionRef: {{ include "ctfd.fullname" . }}
  method: kubernetes
  mount: {{ .Values.secrets.vault.kubernetes.mount }}
  kubernetes:
    role: ctfd-{{ include "ctfd.fullname" . }}
    serviceAccount: {{ include "ctfd.fullname" . }}
  {{- if and .Values.mail.smtp.enabled .Values.mail.smtp.useAuth }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.fullname" . }}-smtp
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.fullname" . }}-smtp
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.fullname" . }}-smtp
  {{- end }}
  {{- if .Values.mail.mailgun.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.fullname" . }}-mailgun
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.fullname" . }}-mailgun
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.fullname" . }}-mailgun
  {{- end }}
  {{- if .Values.oauth.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.fullname" . }}-oauth
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.fullname" . }}-oauth
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.fullname" . }}-oauth
  {{- end }}
  {{- if and .Values.externalRedis.enabled ( not .Values.externalRedis.existingSecret ) -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.redis.redisSecretName" . }}
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.redis.redisSecretName" . }}
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.redis.redisSecretName" . }}
  {{- end }}
  {{- if and .Values.externalDatabase.enabled ( not .Values.externalDatabase.existingSecret ) -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.maridb.databaseSecretName" . }}
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.maridb.databaseSecretName" . }}
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.maridb.databaseSecretName" . }}
  {{- end }}
  {{- if and .Values.externalS3.enabled ( not .Values.s3.s3SecretName ) -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "ctfd.s3.s3SecretName" . }}
spec:
  vaultAuthRef: {{ include "ctfd.fullname" . }}
  mount: {{ .Values.secrets.vault.kubernetes.secrets.mount }}
  type: kv-v2
  path: ctfd/{{ include "ctfd.s3.s3SecretName" . }}
  refreshAfter: 10s
  destination:
    create: true
    name: {{ include "ctfd.s3.s3SecretName" . }}
  {{- end }}
{{- end }}